spring.application.name=interviewdotboot

server.port=8080

spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://127.0.0.1:3307/project_03
spring.datasource.username=project_03
spring.datasource.password=1111

mybatis.mapper-locations= mapper/*.xml
mybatis.type-aliases-package=com.ict.interviewdotboot.vo

# 적절한 길이의 비밀키 사용 (32바이트 길이)
jwt.secret = "abcdefghizABCDEDjklmss1234562342"
jwt.expiration = 3600000

# Spring Security 디버그 로그 활성화
logging.level.org.springframework.security=DEBUG

toss.api.url="https://api.tosspayments.com"
toss.secret.key="test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"