spring.application.name=interviewdotboot

server.port=8080

spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://127.0.0.1:3307/project_03?allowMultiQueries=true
spring.datasource.username=project_03
spring.datasource.password=1111

mybatis.mapper-locations= mapper/*.xml
mybatis.type-aliases-package=com.ict.interviewdotboot.vo

# 적절한 길이의 비밀키 사용 (32바이트 길이)
jwt.secret = "abcdefghizABCDEDjklmss1234562342"
jwt.expiration = 3600000


